### ISSUE TITLE
Handling multiple observation types in a single series / time 

### ISSUE THREAD

**Issue by matt-w-rees** [nicholasjclark/mvgam#39]
Hi Nicholas,

I am wondering if it is possible to have multiple levels of an observation covariate in a single time point for a series. 

For example, two different types of traps set per session. Normally in mgcv I would split this into multiple rows in the dataframe (with same series and time value), but mvgam doesn't seem to like this -- producing 'Error: One or more series in data is missing observations for one or more timepoints'. 

Although perhaps this is less an issue with mvgam, and more how state-space need to be formulated?

Cheers,
Matt.

**Comment by nicholasjclark** [comment]
Hi @matt-w-rees, that is an interesting problem. I'd be most tempted to treat each trap type as a different 'series' and then perhaps let them share the same latent process model (you can see how to do this in the shared states vignette: https://nicholasjclark.github.io/mvgam/articles/shared_states.html. You could then include an effect of trap type in the observation formula, which would hopefully allow you to readily identify the latent process. But you might have to give it a go and let me know what problems you run into, if any!

**Comment by matt-w-rees** [comment]
Thanks Nicholas - I hadn't thought of that approach. I'm not sure it is worthwhile to add another series given there isn't too many times this occurred, so might just add this to the list of things to try down the track.

**Comment by DEHewitt** [comment]
Hi @nicholasjclark, I am getting this same error but with a few differences:

1. I have tagged individuals rather than traps which I have coded as `series`
2. Observations are irregular in time so I am attempting to fit a `CAR()` trend model

I have tried including a `trend_map` as suggested in the link above, but I still get `Error: One or more series in data is missing observations for one or more timepoints`.

My code is here: 
```
trend_map <- data.frame(series = unique(data$series),
                        trend = seq(1, length(unique(data$series))))

m <- mvgam(
  
  # Observation formula
  formula = y ~ series - 1,
  
  # Trend formula
  trend_formula = ~ s(temp, bs = "tp", by = trend),
  
  # Continuous time correlation
  trend_model = CAR(p = 1), noncentred = TRUE,
  
  # Supply a trend map
  trend_map = trend_map,
  
  # Data and observation family
  data = data,
  family = bernoulli(link = "logit"),
  
  # MCMC settings
  burnin = 500,
  samples = 500,
  
  # Use F to not run everything but check things work
  run_model = FALSE
)
```

Ultimately, I want to fit a model that estimates the probability of movement for these individuals. Ideally, it'd be a hierarchical model of the sort that became available recently for `AR()` and `VAR()` trend models, as I have tagged individuals in two size classes and expect that they may respond differently to their environment in terms of movement. Is this possible?

Thanks!
Dan

**Comment by nicholasjclark** [comment]
Hi @DEHewitt, thanks for the message. I currently don't allow trend mapping for continuous time autoregressive states, though clearly I need to implement some more useful error messages to explain that. The problem is that I don't have a sensible way to ensure that the timepoints of the latent state estimates map well to the timepoints of the observation estimates. But there may be other ways I can help you achieve the model you're after. Would you mind explaining a bit more, perhaps as a new thread in the [Discussions](https://github.com/nicholasjclark/mvgam/discussions) so my answers are more visible to other users?
