### ISSUE TITLE
ensemble pooling

### ISSUE THREAD

**Issue by swpease** [nicholasjclark/mvgam#98]
The pooling for `ensemble` happens before the sampling, so the different models' forecasts/hindcasts probably aren't equally weighted.

I wrote an MRE, which I turned into a test that I think ought to pass:

```
test_that("ensemble equal pooling", {
  set.seed(1234)
  mvgam_examp_dat <- sim_mvgam(family = gaussian(),
                               T = 40,
                               prop_missing = 0.1)
  newdat <- mvgam_examp_dat$data_test
  fc <- forecast(object = mvgam:::mvgam_example4,
                 newdata = newdat)
  fc2 <- forecast(object = mvgam:::mvgam_example3,
                  newdata = newdat)

  # replace casts with dummy data
  fc$hindcasts = lapply(fc$hindcasts,
                        \(series_hcs) matrix(4, 1, ncol(series_hcs)))
  fc2$hindcasts = lapply(fc2$hindcasts,
                         \(series_hcs) matrix(5, 10, ncol(series_hcs)))
  fc$forecasts = lapply(fc$forecasts,
                        \(series_fcs) matrix(1, 1, ncol(series_fcs)))
  fc2$forecasts = lapply(fc2$forecasts,
                         \(series_fcs) matrix(2, 10, ncol(series_fcs)))

  n_draws = 2
  fc_ens <- ensemble(fc, fc2, ndraws = n_draws)

  # expected data
  n_rows = n_draws * 2  # 2 models in ensemble
  expected_hc_data = lapply(fc$hindcasts,
                            \(series_hcs) matrix(c(4,4,5,5), n_rows, ncol(series_hcs)))
  expected_fc_data = lapply(fc$forecasts,
                            \(series_fcs) matrix(c(1,1,2,2), n_rows, ncol(series_fcs)))

  expect_equal(fc_ens$hindcasts, expected_hc_data)
  expect_equal(fc_ens$forecasts, expected_fc_data)
})
```

I think the change would be simple:
```
  # Create evenly weighted ensemble hindcasts and forecasts
  ens_hcs <- lapply(seq_len(n_series), function(series){
    do.call(rbind,
            lapply(models,
                   function(x) subsamp(x$hindcasts[[series]], ndraws)))
  })

  ens_fcs <- lapply(seq_len(n_series), function(series){
    do.call(rbind,
            lapply(models,
                   function(x) subsamp(x$forecasts[[series]], ndraws)))
  })
```

And should `ndraws` be less than 5000? That seems large.

**Comment by nicholasjclark** [comment]
Thanks for these suggestions @swpease. I think you make a good point about the need to ensure forecasts are actually being evenly-weighted in the final ensemble, so I re-wrote [the `ensemble` function](https://github.com/nicholasjclark/mvgam/blob/master/R/ensemble.R) to assign weights to each possible draw and then use multinomial sampling for constructing the final ensemble forecast. This is not only better because it doesn't need to do repeat sampling (it will now only take one final sample of `ndraws` from the full pool of weighted draws), but it also provides an easy framework to eventually let users provide specific weights for each component forecast, if they wish to. I also appreciate the test you provided, and I slightly modified it for inclusion (https://github.com/nicholasjclark/mvgam/blob/master/tests/testthat/test-mvgam-methods.R#L342)

**Comment by swpease** [comment]
👍 I'm glad it was helpful. After getting an example working, it seemed like not much more work to make it a test. I was looking at the source code for it because I wasn't sure if all that happens with ensemble-ing forecasts is they get concatenated. Not quite.
